title: "OpenSees-on-DesignSafe Training"
author: "Silvia Mazzoni"
copyright: "2025"
logo: 'logo.png'

only_build_toc_files: true

execute:
  execute_notebooks: "off"

sphinx:
  # Append extra Sphinx extensions without overriding JB defaults
  # extra_extensions:
  #   - sphinx_last_updated_by_git
  #   - sphinx_sitemap
  config:
    suppress_warnings:
      - myst.header
    html_baseurl: "https://silviamazzoni.github.io/training-OpenSees-on-DesignSafe/"
    html_copy_source: true

launch_buttons:
  notebook_interface: "jupyterlab"
  # colab_url: "https://colab.research.google.com"
  thebe: true

repository:
  url: https://github.com/silviamazzoni/training-OpenSees-on-DesignSafe
  branch: main

html:
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
  use_download_button: true
  logo: logo.png
  extra_static_paths:
    - _static
  extra_css:
    - custom.css
  extra_js:
    - custom.js

parse:
  myst_enable_extensions:
    - html_admonition
    - html_image
    - colon_fence
  nb_remove_input_tags: ["remove-input"]
  nb_remove_cell_tags: ["remove-cell"]
  nb_remove_all_outputs_tags: ["remove-output"]
