# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "OpenSees-on-DesignSafe Training"
author: "Silvia Mazzoni"
copyright: "2025"

only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: "off"


tags:
  remove_input: true

sphinx:
  config:
    suppress_warnings:
      - myst.header
    extensions:
      - sphinx_last_updated_by_git
      - sphinx_sitemap
    html_baseurl: "https://silviamazzoni.github.io/training-OpenSees-on-DesignSafe/"
    html_copy_source: true          # enables “.md” (source) in the download menu


launch_buttons:
  notebook_interface: "jupyterlab"
  thebe: true

  
# Information about where the book exists on the web
repository:
  url: https://github.com/silviamazzoni/training-OpenSees-on-DesignSafe # Online location of your book
  # path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
  use_download_button: true
  logo: logo.png
  extra_static_paths:
    - _static
  extra_css:
    - custom.css
  extra_js:
    - custom.js


parse:
  myst_enable_extensions:
    - html_admonition
    - html_image
    - colon_fence
  nb_remove_input_tags: ["remove-input"]
  nb_remove_cell_tags: ["remove-cell"]
  nb_remove_all_outputs_tags: ["remove-output"]

